#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xdg-desktop-portal
Version  : 1.4.2
Release  : 11
URL      : https://github.com/flatpak/xdg-desktop-portal/releases/download/1.4.2/xdg-desktop-portal-1.4.2.tar.xz
Source0  : https://github.com/flatpak/xdg-desktop-portal/releases/download/1.4.2/xdg-desktop-portal-1.4.2.tar.xz
Summary  : Desktop integration portal
Group    : Development/Tools
License  : LGPL-2.1
Requires: xdg-desktop-portal-data = %{version}-%{release}
Requires: xdg-desktop-portal-libexec = %{version}-%{release}
Requires: xdg-desktop-portal-license = %{version}-%{release}
Requires: xdg-desktop-portal-locales = %{version}-%{release}
Requires: xdg-desktop-portal-services = %{version}-%{release}
Requires: xdg-desktop-portal-gtk
BuildRequires : dbus-bin
BuildRequires : geoclue-dev
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(flatpak)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libgeoclue-2.0)
BuildRequires : pkgconfig(libpipewire-0.2)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : sed
BuildRequires : xdg-desktop-portal-gtk
BuildRequires : xmlto

%description
# xdg-desktop-portal
A portal frontend service for [Flatpak](http://www.flatpak.org) and possibly
other desktop containment frameworks.

%package data
Summary: data components for the xdg-desktop-portal package.
Group: Data

%description data
data components for the xdg-desktop-portal package.


%package dev
Summary: dev components for the xdg-desktop-portal package.
Group: Development
Requires: xdg-desktop-portal-data = %{version}-%{release}
Provides: xdg-desktop-portal-devel = %{version}-%{release}
Requires: xdg-desktop-portal = %{version}-%{release}

%description dev
dev components for the xdg-desktop-portal package.


%package libexec
Summary: libexec components for the xdg-desktop-portal package.
Group: Default
Requires: xdg-desktop-portal-license = %{version}-%{release}

%description libexec
libexec components for the xdg-desktop-portal package.


%package license
Summary: license components for the xdg-desktop-portal package.
Group: Default

%description license
license components for the xdg-desktop-portal package.


%package locales
Summary: locales components for the xdg-desktop-portal package.
Group: Default

%description locales
locales components for the xdg-desktop-portal package.


%package services
Summary: services components for the xdg-desktop-portal package.
Group: Systemd services

%description services
services components for the xdg-desktop-portal package.


%prep
%setup -q -n xdg-desktop-portal-1.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569645709
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --disable-pipewire --disable-docbook-docs
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1569645709
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xdg-desktop-portal
cp COPYING %{buildroot}/usr/share/package-licenses/xdg-desktop-portal/COPYING
%make_install
%find_lang xdg-desktop-portal

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Access.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Account.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.AppChooser.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Background.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Email.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.FileChooser.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Inhibit.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Lockdown.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Notification.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.PermissionStore.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Print.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.RemoteDesktop.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Request.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.ScreenCast.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Screenshot.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Session.xml
/usr/share/dbus-1/interfaces/org.freedesktop.impl.portal.Settings.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Account.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Background.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Camera.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Device.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Documents.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Email.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.FileChooser.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.GameMode.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Inhibit.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Location.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.NetworkMonitor.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Notification.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.OpenURI.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Print.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.ProxyResolver.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.RemoteDesktop.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Request.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.ScreenCast.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Screenshot.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Session.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Settings.xml
/usr/share/dbus-1/interfaces/org.freedesktop.portal.Trash.xml
/usr/share/dbus-1/services/org.freedesktop.impl.portal.PermissionStore.service
/usr/share/dbus-1/services/org.freedesktop.portal.Desktop.service
/usr/share/dbus-1/services/org.freedesktop.portal.Documents.service

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/xdg-desktop-portal.pc

%files libexec
%defattr(-,root,root,-)
/usr/libexec/xdg-desktop-portal
/usr/libexec/xdg-document-portal
/usr/libexec/xdg-permission-store

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xdg-desktop-portal/COPYING

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/xdg-desktop-portal.service
/usr/lib/systemd/user/xdg-document-portal.service
/usr/lib/systemd/user/xdg-permission-store.service

%files locales -f xdg-desktop-portal.lang
%defattr(-,root,root,-)

